<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>$(CopyGifWindowsTargetFramework)</TargetFramework>
		<SupportedOSPlatformVersion>$(CopyGifWindowsMinimumVersion)</SupportedOSPlatformVersion>
		<UseWindowsForms>true</UseWindowsForms>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\CopyGIF.Core\CopyGIF.Core.csproj" />
	</ItemGroup>

</Project>