<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(CopyGifNetTargetFramework)</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CopyGIF.Application\CopyGIF.Application.csproj" />
    <ProjectReference Include="..\CopyGIF.Core\CopyGIF.Core.csproj" />
  </ItemGroup>

</Project>